pipeline {
    agent any

    parameters {
        string(
            name: 'FRONTEND_DOCKER_TAG',
            defaultValue: '',
            description: 'Frontend Docker image tag from CI'
        )

        string(
            name: 'BACKEND_DOCKER_TAG',
            defaultValue: '',
            description: 'Backend Docker image tag from CI'
        )
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Verify Image Tags') {
            steps {
                echo "Frontend tag: ${params.FRONTEND_DOCKER_TAG}"
                echo "Backend tag: ${params.BACKEND_DOCKER_TAG}"
            }
        }

        stage('Update Kubernetes Manifests') {
            steps {
                sh """
                    sed -i "s|image: fazal6762/wanderlust-backend:.*|image: fazal6762/wanderlust-backend:${params.BACKEND_DOCKER_TAG}|" kubernetes/backend.yaml

                    sed -i "s|image: fazal6762/wanderlust-frontend:.*|image: fazal6762/wanderlust-frontend:${params.FRONTEND_DOCKER_TAG}|" kubernetes/frontend.yaml
                """
            }
        }

        stage('Git Push') {
            steps {
                withCredentials([
                    gitUsernamePassword(
                        credentialsId: 'Github-cred',
                        gitToolName: 'Default'
                    )
                ]) {
                    sh '''
                        git config user.name "Jenkins"
                        git config user.email "jenkins@localhost"

                        git add kubernetes/backend.yaml kubernetes/frontend.yaml

                        git commit -m "Update application image versions"

                        git push origin HEAD:main
                    '''
                }
            }
        }
    }

    post {
        success {
            echo 'CD successful: Kubernetes manifests updated and pushed to GitHub.'
        }

        failure {
            echo 'CD pipeline failed.'
        }
    }
}